---

# Building by following: https://docs.opencv.org/4.7.0/d4/da1/tutorial_js_setup.html

- name: Install required packages
  become_user: 'root'
  ansible.builtin.apt:
    name:
      - 'git'
      - 'jq'
    state: 'latest'

- name: Git checkout for opencv
  ansible.builtin.git:
    repo: 'https://github.com/opencv/opencv.git'
    dest: /opt/opencv
    version: '4.7.0'
    depth: 1
    force: true

- name: Git checkout for opencv_contrib
  ansible.builtin.git:
    repo: 'https://github.com/opencv/opencv_contrib'
    dest: /opt/opencv_contrib
    version: '4.7.0'
    depth: 1
    force: true

# Custom build of opencv.js

# References:
# - https://forum.opencv.org/t/cannot-load-virtual-class-tracking-algorithm-in-compiled-opencv-js/6093
# - https://github.com/ganwenyao/opencv_js
# - https://github.com/opencv/opencv/blob/4.x/platforms/js/build_js.py
# - https://forum.opencv.org/t/opencv-js-build-tracking-module-in-opencv-contrib-but-encounter-generate-error/608

- name: Update build config for intensity_transform to include js
  ansible.builtin.lineinfile:
    path: /opt/opencv_contrib/modules/intensity_transform/CMakeLists.txt
    regexp: '^ocv_define_module\(intensity_transform opencv_core opencv_imgproc WRAP python'
    line: 'ocv_define_module(intensity_transform opencv_core opencv_imgproc WRAP python js)'
    state: present
    insertafter: 'EOF'

- name: Update build config for js core bindings to add intensity_transform
  ansible.builtin.lineinfile:
    path: /opt/opencv/modules/js/src/core_bindings.cpp
    regexp: '^using namespace cv::intensity_transform;'
    line: 'using namespace cv::intensity_transform;'
    state: present
    insertafter: '^using namespace cv;$'

- name: Update build config for js to add intensity_transform
  ansible.builtin.lineinfile:
    path: /opt/opencv/platforms/js/opencv_js.config.py
    regexp: '^intensity_transform '
    line: "intensity_transform = {'': ['autoscaling', 'gammaCorrection', 'logTransform']}"
    state: present
    insertbefore: '^white_list ='

- name: Update build config for js to add intensity_transform to include list
  ansible.builtin.lineinfile:
    path: /opt/opencv/platforms/js/opencv_js.config.py
    regexp: '^white_list ='
    line: "white_list = makeWhiteList([core, imgproc, objdetect, video, dnn, features2d, photo, calib3d, intensity_transform])"
    state: present

# For debugging
- name: Remove build dirs
  ansible.builtin.file:
    path: '/opt/opencv/{{ item }}'
    state: absent
  loop:
    - build_js
    - build_wasm

# TODO: other arguments to consider:
# --build_wasm --simd --webnn --build_test --build_loader --build_perf
# --clean_build_dir
- name: Build opencv.js variants
  ansible.builtin.command:
    cmd: >-
      docker run --rm -u 1000:1000
      -v /opt/opencv:/src -v /opt/opencv_contrib:/src_contrib
      emscripten/emsdk:2.0.10 emcmake
      python3 ./platforms/js/build_js.py
      {{ item }} --cmake_option="-DOPENCV_EXTRA_MODULES_PATH=/src_contrib/modules"
  register: opencv_js_cmd_output
  loop:
    - build_js
#    - build_wasm --build_wasm

# Add this at the top of opencv.js:
#  // OpenCV.js v4.7.0
#  // Custom build, includes 'intensity_transform'

- name: Save opencv.js build output
  become_user: 'root'
  ansible.builtin.template:
    src: 'opencv_js_build_output.txt'
    dest: '/opt/opencv_js_build_output.txt'
    force: true
    backup: false
    owner: 'root'
    group: 'root'
    mode: 'u=rw,g=r,o=r'

# TODO: the node tests don't seem to work
#- name: Install npm opencv dependencies
#  ansible.builtin.command:
#    cmd: npm install
#    chdir: /opt/opencv/build_js/bin
#
#- name: Run opencv tests using nodejs
#  ansible.builtin.command:
#    cmd: node tests.js
#    chdir: /opt/opencv/build_js/bin

